-- ==============================================================================
-- SYNC COMPLETE REAL PORTFOLIO (32 PROYEK, 4 KATEGORI, PENGALAMAN & LAYANAN ASLI)
-- ==============================================================================

-- 1. Ubah tipe kolom ID menjadi TEXT agar string ID didukung penuh
ALTER TABLE public.project_images DROP CONSTRAINT IF EXISTS project_images_project_id_fkey;
ALTER TABLE public.projects DROP CONSTRAINT IF EXISTS projects_category_id_fkey;

ALTER TABLE public.categories ALTER COLUMN id TYPE TEXT;
ALTER TABLE public.projects ALTER COLUMN id TYPE TEXT;
ALTER TABLE public.projects ALTER COLUMN category_id TYPE TEXT;
ALTER TABLE public.project_images ALTER COLUMN id TYPE TEXT;
ALTER TABLE public.project_images ALTER COLUMN project_id TYPE TEXT;
ALTER TABLE public.experiences ALTER COLUMN id TYPE TEXT;
ALTER TABLE public.services ALTER COLUMN id TYPE TEXT;
ALTER TABLE public.site_settings ALTER COLUMN id TYPE TEXT;
ALTER TABLE public.profiles ALTER COLUMN id TYPE TEXT;

ALTER TABLE public.projects ADD CONSTRAINT projects_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE SET NULL;
ALTER TABLE public.project_images ADD CONSTRAINT project_images_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

-- 2. Hapus data dummy template lama
DELETE FROM public.project_images;
DELETE FROM public.projects;
DELETE FROM public.categories;
DELETE FROM public.experiences;
DELETE FROM public.services;
DELETE FROM public.profiles;

-- 3. Masukkan Profil Asli Bernardus Firman
INSERT INTO public.profiles (
  id, full_name, title, tagline, bio, years_experience, avatar_url, cv_url,
  location, email, phone, available_for_hire, availability_note
) VALUES (
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  'Bernardus Firman Bagaskara',
  'Graphic Designer',
  'Berpengalaman 5+ tahun sebagai desainer grafis dan di bidang digital printing.',
  'Graphic Designer dengan pengalaman sejak 2022 dan telah mengerjakan 500+ proyek desain untuk kebutuhan branding, promosi, media sosial, dan digital printing. Terbiasa menangani proses desain secara end-to-end, mulai dari menerjemahkan brief menjadi konsep visual, menyusun layout, memilih tipografi dan elemen visual, melakukan revisi, hingga menghasilkan final artwork siap publikasi dan produksi. Menguasai Adobe Photoshop, Adobe Illustrator, CorelDRAW, Adobe Premiere Pro, Adobe After Effects, dan CapCut untuk mengembangkan desain statis maupun konten video. Berorientasi pada ketepatan brief, kualitas visual, konsistensi brand, dan penyelesaian pekerjaan sesuai deadline.',
  5,
  '/profile.jpg',
  '/cv-bernardusfirman.pdf',
  'Trosobo, Sambi, Boyolali, Jawa Tengah',
  'bernardusfirman@gmail.com',
  '+62 821-3560-2758',
  true,
  'Terbuka untuk proyek branding, promosi, video, dan digital printing'
);

-- 4. Masukkan 4 Kategori Asli
INSERT INTO public.categories (id, name, slug, description, sort_order) VALUES
('cat-desain-logo', 'Desain Logo', 'desain-logo', 'Koleksi desain identitas visual, logo maskot, badge emblem, dan branding kreatif untuk UMKM, organisasi, kuliner, dan brand modern.', 1),
('cat-desain-feeds', 'Desain Feeds', 'desain-feeds', 'Koleksi desain feed Instagram, carousel promosi, materi iklan digital, dan visual kampanye media sosial dengan layout modern dan memikat.', 2),
('cat-desain-banner', 'Desain Banner', 'desain-banner', 'Koleksi desain spanduk outdoor, standing X-banner, roll-up banner, backdrop promosi, signboard gerai, dan materi promosi cetak digital printing.', 3),
('cat-desain-label-packaging', 'Desain Label & Packaging', 'desain-label-packaging', 'Koleksi desain kemasan produk, kotak take-away (food packaging), die-cut box, label stiker botol, jar makanan, dan rancangan pola dieline siap cetak.', 4);

-- 5. Masukkan 32 Proyek Asli
INSERT INTO public.projects (
  id, title, slug, subtitle, description, challenge, solution, results,
  client, year, role, category_id, tags, cover_image, live_url, behance_url,
  featured, sort_order, status
) VALUES
('proj-logo-1', 'Karang Taruna Selo Utomo', 'karang-taruna-selo-utomo', 'Desain identitas & logo organisasi kepemudaan bernuansa kultural lokal', 'Desain logo untuk organisasi kepemudaan Karang Taruna Selo Utomo yang memadukan unsur tradisional siluet wayang/topeng dengan ornamen dinamis modern. Menggambarkan semangat kebersamaan, kreativitas generasi muda, dan keluhuran budaya lokal dengan karakter visual yang kuat, berwibawa, dan mudah dikenali.', 'Menciptakan representasi identitas kepemudaan desa yang berakar pada nilai-nilai tradisi leluhur (Selo Utomo) tanpa terkesan kaku, melainkan luwes, energik, dan membanggakan bagi generasi muda.', 'Mengembangkan ornamen stilasi wayang dengan lekukan tegas berpadu gelombang merah muda yang harmonis, disertai tipografi sans-serif modern yang tegas, kokoh, dan berkarakter kepemimpinan.', 'Diresmikan sebagai identitas resmi Karang Taruna Selo Utomo untuk seragam, bendera, media sosial, serta seluruh publikasi kegiatan sosial kemasyarakatan.', 'Karang Taruna Selo Utomo', 2024, 'Lead Logo Designer & Brand Identity', 'cat-desain-logo', ARRAY['Desain Logo', 'Karang Taruna', 'Budaya', 'Identitas Visual', 'Organisasi'], '/portfolio/logos/page-1.png', NULL, NULL, true, 1, 'published'),
('proj-logo-2', 'Hype Steps', 'hype-steps', 'Logo modern & dinamis untuk brand streetwear & sneakers masa kini', 'Konsep logo energik untuk Hype Steps yang terinspirasi dari siluet langkah kaki cepat, gelombang dinamis, dan kultur streetwear urban. Garis-garis tegas mencerminkan kecepatan, gaya hidup aktif, dan tren kekinian yang digemari anak muda pecinta sneakers.', 'Menciptakan logo yang tajam dan ikonik yang dapat diaplikasikan dengan sangat baik pada berbagai media: bordir sepatu, sablon kaos, sol karet, hingga kemasan kotak sepatu.', 'Merancang monogram siluet langkah dinamis dengan sapuan garis kecepatan horizontal serta tipografi sans-bold berkarakter street culture yang futuristik dan percaya diri.', 'Meningkatkan daya tarik visual brand di kalangan pecinta sneakers dan menjadi elemen signature pada rilisan apparel Hype Steps.', 'Hype Steps Footwear & Streetwear', 2024, 'Brand Identity & Logo Designer', 'cat-desain-logo', ARRAY['Desain Logo', 'Streetwear', 'Fashion', 'Sneakers', 'Modern Typography'], '/portfolio/logos/page-2.png', NULL, NULL, true, 2, 'published'),
('proj-logo-3', 'Sambel Oma', 'sambel-oma', 'Desain maskot logo kuliner tradisional nusantara resep warisan nenek', 'Desain maskot logo Sambel Oma dengan karakter nenek berkacamata ramah yang sedang mengulek sambal segar dalam cobek batu dengan cabai merah menyala. Membangun kehangatan, cita rasa otentik warisan keluarga, dan kualitas bumbu khas tradisional nusantara yang menggugah selera.', 'Menghadirkan sosok maskot nenek yang ramah, hangat, dan terpercaya tanpa terlihat terlalu rumit, sehingga tetap jelas dan kontras saat dicetak pada label botol sambal ukuran kecil.', 'Mengembangkan ilustrasi maskot vektor bergaya kartun vintage penuh ekspresi, dipadukan tipografi kasual tebal bertekstur selera kuliner nusantara yang menggoda lidah.', 'Mendongkrak pengenalan merek pada kemasan botol sambal kemasan di pasar ritel dan marketplace, memberikan kesan kuliner rumahan otentik yang higienis.', 'Sambel Oma Nusantara', 2024, 'Mascot Illustrator & Logo Designer', 'cat-desain-logo', ARRAY['Desain Logo', 'Maskot Kuliner', 'Sambel Nusantara', 'UMKM', 'Label Kemasan'], '/portfolio/logos/page-3.png', NULL, NULL, true, 3, 'published'),
('proj-logo-4', 'Sop Tangkar Pak Dhe', 'sop-tangkar-pak-dhe', 'Desain maskot logo kuliner legendaris sop tangkar daging sapi iga gurih', 'Visual logo maskot Sop Tangkar Pak Dhe menampilkan figur bapak/pak dhe berkumis ramah dengan mangkuk sop tangkar gurih yang mengepul hangat. Mengedepankan kesan selera makan yang menggugah, lezat, legendaris, dan merakyat.', 'Menciptakan citra kuliner tradisional legendaris yang bersahabat namun memiliki daya pikat profesional untuk warung makan dan cabang kuliner.', 'Ilustrasi maskot koki lokal legendaris dengan apron putih dan mangkuk kuah beraroma sedap, dibingkai tipografi bold bersudut lengkung khas makanan lezat.', 'Sukses diterapkan pada neon box resto, spanduk warung, seragam karyawan, dan stiker kemasan take-away.', 'Sop Tangkar Pak Dhe', 2024, 'Mascot & Logo Designer', 'cat-desain-logo', ARRAY['Desain Logo', 'Maskot Makanan', 'Sop Tangkar', 'Kuliner Nusantara', 'Warung Tradisional'], '/portfolio/logos/page-4.png', NULL, NULL, true, 4, 'published'),
('proj-logo-5', 'Ruchi', 'ruchi', 'Logo maskot imut & manis untuk brand cookies, pastry, & bakery', 'Karakter maskot kucing menggemaskan yang sedang menikmati kue kering (cookies), dipadukan dengan tipografi playful dan lembut. Menciptakan identitas manis, ramah, dan memikat bagi anak-anak dan pencinta camilan manis.', 'Membuat maskot yang menggemaskan dan ramah dengan garis outline bersih sehingga mudah dicetak pada toples cookies, paper bag, dan packaging box.', 'Desain maskot kucing berpose santai mengunyah cookie dengan remah biskuit kecil, didukung lettering Ruchi berlekuk manis seperti adonan kue lezat.', 'Memperkuat branding produk cookies premium home-made dan meningkatkan ketertarikan pembeli di hampers hari raya serta penjualan harian.', 'Ruchi Cookies & Bakery', 2024, 'Mascot Character & Logo Designer', 'cat-desain-logo', ARRAY['Desain Logo', 'Maskot Kucing', 'Bakery', 'Cookies', 'Playful Character'], '/portfolio/logos/page-5.png', NULL, NULL, true, 5, 'published'),
('proj-logo-6', 'Little Tokyo', 'little-tokyo', 'Desain logo maskot Japanese culinary & sushi bar yang ceria', 'Logo bergaya anime/manga Jepang dengan maskot Maneki Neko (kucing pembawa keberuntungan) menikmati hidangan sushi roll, ramen, dan sake. Dominasi warna merah menyala dan aksen khas Jepang menyampaikan atmosfer kedai makanan Jepang yang ramai, otentik, dan lezat.', 'Menggabungkan aneka menu khas Jepang (sushi, ramen, sake) ke dalam satu komposisi maskot yang seimbang, padat, dan estetis tanpa terkesan berantakan.', 'Menempatkan karakter kucing hoki di tengah dengan piring sushi dan mangkuk ramen di depan, dilengkapi banner bertuliskan huruf kanji Oishii (lezat) dan font tebal berkarakter Little Tokyo.', 'Menjadi ikon utama resto Jepang yang sangat instagrammable, dipakai pada sign board kedai, daftar menu, hingga merchandise stiker.', 'Little Tokyo Resto & Sushi Bar', 2024, 'Japanese Style Mascot & Brand Designer', 'cat-desain-logo', ARRAY['Desain Logo', 'Japanese Food', 'Maneki Neko', 'Sushi & Ramen', 'Restoran Jepang'], '/portfolio/logos/page-6.png', NULL, NULL, true, 6, 'published'),
('proj-logo-7', 'Roti Bang Boy', 'roti-bang-boy', 'Logo vintage badge untuk brand roti & pastry fresh harian', 'Desain emblem badge melingkar bergaya retro ramah dengan maskot anak laki-laki bertopi baker. Memberikan kesan produk roti segar buatan tangan setiap hari dengan harga bersahabat dan kualitas premium yang dicintai keluarga.', 'Membuat logo emblem minimalis 2-warna (merah dan putih) yang tajam, rapi, dan mudah disablon pada plastik kemasan roti serta cap stempel kertas roti.', 'Line art vektor melingkar dengan ilustrasi anak laki-laki tersenyum ramah memakai topi cap baker, dipadukan tipografi Roti Bang Boy yang tegap dan kokoh.', 'Kemasan roti tampil bersih, klasik, dan mudah diingat konsumen di puluhan gerai mitra reseller.', 'Roti Bang Boy Bakery', 2024, 'Badge Logo & Mascot Designer', 'cat-desain-logo', ARRAY['Desain Logo', 'Badge Logo', 'Bakery', 'Roti Harian', 'Vintage Line Art'], '/portfolio/logos/page-7.png', NULL, NULL, true, 7, 'published'),
('proj-logo-8', 'Ayam Nenek', 'ayam-nenek', 'Desain logo maskot ayam goreng & panggang resep otentik nenek', 'Maskot nenek berjilbab kuning ramah sedang memeluk hidangan ayam goreng utuh yang renyah dan gurih. Menghadirkan rasa nostalgia masakan rumahan seorang nenek yang penuh cinta, lezat, halal, dan penuh berkah.', 'Menonjolkan nilai kehangatan keluarga dan kehalalan produk ayam goreng kampung dengan visual maskot yang ceria dan menonjol di pinggir jalan.', 'Pilihan palet warna kuning keemasan dan merah hangat yang memicu selera makan, dengan figur nenek berkerudung ceria memeluk ayam olahan keemasan.', 'Meningkatkan daya tarik outlet resto Ayam Nenek dan pesanan katering nasi kotak untuk berbagai acara syukuran dan hajatan.', 'Ayam Nenek Resto & Catering', 2024, 'Mascot Character & Logo Designer', 'cat-desain-logo', ARRAY['Desain Logo', 'Maskot Kuliner', 'Ayam Goreng', 'Halal Food', 'Catering'], '/portfolio/logos/page-8.png', NULL, NULL, true, 8, 'published'),
('proj-logo-9', 'Sahabat Sego Sambel', 'sahabat-sego-sambel', 'Desain logo fiery & bold untuk spesialis sego sambel pedas mantap', 'Ilustrasi kobaran api membara di atas cobek cabai rawit dengan tipografi bold yang bertenaga. Sangat efektif merefleksikan sensasi rasa pedas yang membakar lidah, nikmat, dan menjadi favorit para pecinta kuliner pedas nusantara.', 'Mengkomunikasikan tingkat kepedasan ekstrem dan kelezatan sego sambel secara visual instan melalui logo yang mencolok dari kejauhan.', 'Kombinasi elemen api berkobar dinamis, cabai merah runcing, dan cobek tradisional dengan outline hitam tebal dan tipografi Sahabat Sego Sambel berlekuk dinamis.', 'Menjadi signature brand untuk gerai sego sambel, diaplikasikan pada plang nama outlet, seragam tim, dan kemasan bungkusan makanan.', 'Sahabat Sego Sambel', 2024, 'Brand Identity & Logo Designer', 'cat-desain-logo', ARRAY['Desain Logo', 'Sego Sambel', 'Pedas', 'Kuliner Nusantara', 'Fiery Mascot'], '/portfolio/logos/page-9.png', NULL, NULL, true, 9, 'published'),
('proj-logo-10', 'Bebek Mas Bolot', 'bebek-mas-bolot', 'Desain maskot logo kuliner olahan bebek dengan visual ceria & memikat', 'Desain logo maskot untuk Bebek Mas Bolot yang memadukan karakter figur pemilik berkacamata ramah berdampingan dengan maskot bebek putih yang ceria dan akrab. Mengusung warna merah menyala dan aksen kuning yang menggugah nafsu makan, identitas ini dirancang untuk menciptakan daya ingat yang kuat, kesan bersahabat, serta menonjolkan kualitas kuliner olahan bebek yang lezat dan otentik.', 'Menciptakan perpaduan karakter wajah pemilik dan maskot bebek dalam satu kesatuan badge melingkar yang harmonis, ekspresif, dan tidak terlalu rumit, sehingga tetap tajam, mudah dikenali, dan kontras saat dicetak pada neon box gerai, spanduk, seragam, hingga label stiker kemasan cup dan box makanan.', 'Mengembangkan ilustrasi maskot vektor kartun penuh kehangatan dengan outline tegas, palet warna berani (merah marun, putih, dan kuning), serta tipografi kustom tebal melengkung khas kuliner nusantara yang eye-catching, dinamis, dan sangat cocok untuk berbagai format media cetak maupun digital.', 'Menghasilkan identitas visual yang profesional dan ikonik untuk brand kuliner Bebek Mas Bolot, meningkatkan daya tarik gerai, serta memperkuat loyalitas dan kepercayaan konsumen saat peluncuran produk dan penjualan online.', 'Bebek Mas Bolot Kuliner', 2024, 'Mascot Illustrator & Logo Designer', 'cat-desain-logo', ARRAY['Desain Logo', 'Maskot Kuliner', 'Bebek Mas Bolot', 'UMKM Kuliner', 'Food Branding'], '/portfolio/logos/page-10.png', NULL, NULL, true, 10, 'published'),
('proj-feed-4', 'Bebek Mas Bolot Feeds', 'bebek-mas-bolot-feeds', 'Desain feed Instagram kuliner nusantara bercita rasa gurih pedas & visual promo pesan daring', 'Paket desain feed promosi Instagram untuk outlet kuliner Bebek Mas Bolot. Berfokus pada kelezatan menu signature seperti Bebek Utuh Bumbu Hitam, Bebek Jumbo Laos, Ayam Bumbu Hitam, dan Bebek Bakar dengan sambal pedas membakar lidah, serta kemudahan order melalui fitur "Tinggal Tap, Langsung Santap".', 'Membuat foto olahan bebek dan ayam terlihat sangat lezat dan menggoda selera di layar smartphone, sekaligus mengarahkan konversi audiens agar segera melakukan pemesanan via delivery app.', 'Menerapkan nuansa warna merah cabai membara dengan ornamen kepulan asap hangat dan tekstur bumbu rempah hitam yang pekat. Menambahkan mockup tampilan smartphone pemesanan instan serta badge menu ukuran jumbo yang mempertegas nilai kepuasan porsi makan.', 'Sukses mendorong lonjakan order takeaway dan delivery saat jam makan siang dan makan malam, serta meningkatkan jumlah follower akun media sosial Bebek Mas Bolot secara organik.', 'Bebek Mas Bolot Kuliner', 2024, 'Food Social Media Specialist & Banner Designer', 'cat-desain-feeds', ARRAY['Desain Feeds', 'Kuliner Bebek', 'Promo Kuliner', 'Bumbu Hitam', 'Food Promotion'], '/portfolio/feeds/feed-bebek-mas-bolot.png', NULL, NULL, true, 11, 'published'),
('proj-feed-1', 'Airlangga Gymnasium', 'airlangga-gymnasium-feeds', 'Desain feed Instagram & visual campaign fitness bernuansa dinamis, bold, & bertenaga', 'Seri desain konten media sosial dan feed Instagram untuk Airlangga Gymnasium. Mengombinasikan tipografi headline tebal bergaya sport poster dengan palet warna hitam dan kuning cerah (high-visibility). Setiap postingan dirancang untuk memacu semangat berolahraga, mulai dari edukasi gerakan latihan, motivasi konsistensi, hingga program keanggotaan gym.', 'Membangun visual feed yang atraktif dan energik di tengah padatnya feed Instagram kebugaran, sekaligus menyampaikan informasi teknik gerakan dan edukasi nutrisi secara padat, jelas, dan memotivasi audiens untuk datang berlatih.', 'Menerapkan tata letak visual modern bertema industrial sport dengan kontras tinggi (kuning neon dan hitam pekat), tipografi sans-serif ultra-bold, efek pencahayaan dramatis pada fotografi model atlet, serta sistem grid micro-content yang rapi dan mudah dibaca saat scrolling.', 'Meningkatkan engagement rate akun Instagram hingga 65%, memperkuat persepsi profesional gym, serta menarik peningkatan pendaftaran member baru melalui kampanye visual bertema konsistensi latihan.', 'Airlangga Gymnasium', 2024, 'Social Media Designer & Content Strategist', 'cat-desain-feeds', ARRAY['Desain Feeds', 'Fitness & Gym', 'Instagram Carousel', 'Social Media Branding', 'Sport Campaign'], '/portfolio/feeds/feed-airlangga.png', NULL, NULL, true, 12, 'published'),
('proj-feed-5', 'Griya Nyushi Japanese Food', 'griya-nyushi-japanese-feeds', 'Desain feed Instagram resto Jepang bernuansa biru autentik, semarak lentera, & sajian sushi segar', 'Desain feed Instagram tematik untuk restoran Jepang Griya Nyushi "Japanese Food & Sushi". Mengangkat keindahan budaya kuliner negeri sakura dengan sajian menu favorit seperti Tempura renyah, Sashimi salmon segar, Temaki roll, dan Nigiri sushi, dihiasi ornamen lentera merah chouchin dan bunga sakura merekah.', 'Menyampaikan suasana hangat kedai sushi Jepang yang otentik, higienis, dan ramah kantong bagi kalangan muda dan keluarga, dengan visual menu yang segar dan tampak premium.', 'Memilih palet biru laut Jepang (traditional Japanese indigo) yang menonjolkan kesegaran irisan ikan salmon dan tuna, dipadukan tipografi kuas berkarakter kaligrafi oriental modern, ornamen lampion bercahaya hangat, serta foto staf resto yang menyambut pelanggan dengan ramah.', 'Menciptakan citra resto sushi yang estetik dan instagrammable, mendongkrak kunjungan dine-in pelanggan baru, serta memperkuat layanan pesan antar makanan Jepang di wilayah lokal.', 'Griya Nyushi Resto', 2024, 'Social Media Designer & Japanese Brand Stylist', 'cat-desain-feeds', ARRAY['Desain Feeds', 'Japanese Food', 'Sushi & Sashimi', 'Resto Branding', 'Asian Culinary'], '/portfolio/feeds/feed-griya-nyushi.png', NULL, NULL, true, 13, 'published'),
('proj-feed-3', 'Roti Bang Boy Feeds', 'roti-bang-boy-feeds', 'Desain feed Instagram kuliner bakery menggugah selera dengan nuansa ceria & warm vintage', 'Koleksi desain feed Instagram untuk Roti Bang Boy dengan konsep visual yang menggoda selera (appetizing) dan penuh kehangatan roti fresh-from-the-oven. Menyoroti kelembutan tekstur roti, aneka varian pastry seperti cinnamon roll, croissant, dan roti kepang tabur gula, lengkap dengan call-to-action pesan sekarang.', 'Menampilkan detail tekstur kelezatan roti yang renyah dan lembut secara visual agar langsung memicu keinginan audiens untuk ngemil roti, dengan gaya ramah keluarga yang konsisten dengan maskot Roti Bang Boy.', 'Menggunakan dominasi warna merah cerah berpadu pola taplak catur (gingham) merah-putih, aksen lelehan selai cokelat dan remah pastry, serta tipografi pop-casual yang playful seperti "Sarapan Asyik", "Teman Ngemil", dan "Lembutnya Juara".', 'Interaksi audiens pada feed meningkat drastis, meningkatkan pesanan harian melalui WhatsApp dan aplikasi pesan-antar daring, serta memperkuat loyalitas pelanggan penikmat roti harian.', 'Roti Bang Boy Bakery', 2024, 'Social Media Content Creator & Food Layout', 'cat-desain-feeds', ARRAY['Desain Feeds', 'Bakery & Pastry', 'Kuliner Roti', 'Food Social Media', 'Playful Feeds'], '/portfolio/feeds/feed-roti-bang-boy.png', NULL, NULL, true, 14, 'published'),
('proj-feed-2', 'CloveCare Daily Skincare', 'clovecare-skincare-feeds', 'Desain feed Instagram aesthetic, clean, & fresh untuk kampanye produk skincare & promo marketplace', 'Desain rangkaian feed Instagram bernuansa soft aquatic blue & clean white untuk brand perawatan kulit CloveCare. Menampilkan etalase produk hydrating serum, visual ritual perawatan harian (daily hydration ritual), serta materi promosi belanja online kembar (11.11, 12.12 Skin Goals Sale, dan Year End Super Sale).', 'Menciptakan citra brand skincare yang menenangkan, higienis, dan terpercaya tanpa terkesan monoton, sekaligus harus mampu mengakomodasi layout promosi diskon marketplace (Shopee Mall) yang komersial dan eye-catching.', 'Menggabungkan elemen visual cipratan air segar (water splash), pencahayaan natural lembut, serta model perempuan berhijab dan kasual. Tipografi elegan dipadukan dengan badge promo marketplace yang terstruktur rapi agar pesan diskon tersampaikan tanpa merusak estetika mewah brand.', 'Mendongkrak performa kampanye musiman akhir tahun di media sosial, menghasilkan conversion rate klik bio yang tinggi ke toko Shopee Mall, dan memperkuat identitas brand skincare premium.', 'CloveCare Beauty', 2024, 'Creative Content & Social Media Designer', 'cat-desain-feeds', ARRAY['Desain Feeds', 'Skincare Beauty', 'Aesthetic Feed', 'Promo Marketplace', 'Clean Design'], '/portfolio/feeds/feed-clovecare.png', NULL, NULL, true, 15, 'published'),
('proj-banner-1', 'Amanah Frozen Food Banner', 'amanah-frozen-food-banner', 'Desain spanduk gerai & standing banner produk frozen food UMKM dengan visual renyah & menggoda', 'Set desain banner promosi untuk gerai Amanah Frozen Food yang mencakup spanduk horizontal depan toko dan standing banner vertikal. Menampilkan daftar varian produk frozen food favorit seperti bakso, nugget, sosis, tempura, otak-otak, disertai foto olahan gorengan krispi keemasan dan informasi kontak WhatsApp yang kontras dan jelas.', 'Menciptakan desain banner luar ruang (outdoor) yang informatif dan mencolok dari kejauhan di pinggir jalan raya, dengan keterbacaan teks daftar produk yang tinggi dan foto makanan yang memancing selera konsumen.', 'Menerapkan palet warna merah menyala dan kuning cerah khas selera kuliner, tipografi sans-serif tebal dengan outline kontras, serta foto piring nugget dan tempura goreng beresolusi tinggi dengan pencahayaan hangat.', 'Meningkatkan visibilitas toko dari pengendara jalan raya, mempermudah pelanggan memilih varian produk tanpa ragu, dan meningkatkan transaksi harian gerai frozen food.', 'Amanah Frozen Food', 2024, 'Print & Digital Banner Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'Spanduk Gerai', 'Standing Banner', 'Frozen Food', 'Digital Printing'], '/portfolio/banners/banner-1.png', NULL, NULL, true, 16, 'published'),
('proj-banner-2', 'Rocket Chicken Promo Banners', 'rocket-chicken-promo-banners', 'Seri standing X-banner promo paket hemat & best seller gerai fast food Rocket Chicken', 'Seri 4 desain roll-up / X-banner vertikal untuk outlet Rocket Chicken yang mempromosikan aneka paket favorit: Paket Hesa (Burger + French Fries + Milo), Paket Duo (Nasi Goreng + Mie Goreng + 2 Sayap + 2 Fruit Tea), Paket Once, dan Paket Couple. Dilengkapi badge Best Seller bintang lima, penegasan harga terjangkau, serta channel pesan antar (ShopeeFood, GoFood, GrabFood).', 'Menyusun komposisi vertikal yang padat informasi (nama paket, detail isi menu, harga hemat, foto produk, dan badge online delivery) agar tetap terorganisir rapi dan nyaman dilihat pelanggan yang sedang mengantre di depan kasir.', 'Menggunakan sistem hierarki visual berjenjang: header merah cerah dengan rating bintang, badge harga miring warna merah-kuning yang menonjol, foto sajian makanan berlatar meja kayu bersih, serta footer informasi layanan pesan antar 24/7.', 'Mempercepat proses pemesanan konsumen di kasir gerai berkat kejelasan paket hemat, serta mendongkrak penjualan rata-rata menu bundling (combo meal) hingga 35%.', 'Rocket Chicken Franchise Partner', 2024, 'Promotional Standing Banner Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'X-Banner Promo', 'Fast Food', 'Rocket Chicken', 'Menu Display'], '/portfolio/banners/banner-2.png', NULL, NULL, true, 17, 'published'),
('proj-banner-3', 'Sop Tangkar Pak Dhe Signage & Banners', 'sop-tangkar-pak-dhe-banners', 'Paket lengkap spanduk outlet, papan penunjuk arah, & X-banner paket maksi hemat', 'Paket komprehensif desain materi promosi cetak untuk rumah makan Sop Tangkar Pak Dhe. Meliputi spanduk plang nama spesialis sop iga, spanduk selamat datang dengan kutipan ramah, sepasang papan rambu petunjuk arah kanan-kiri (Cuma Rp 20.000), serta X-banner promo "Maksi Hemat Bareng Besti" paket lengkap sop tangkar dan es teh manis.', 'Menciptakan konsistensi branding tradisional nusantara di berbagai format media cetak outdoor yang berbeda ukuran, mulai dari plang lebar, papan petunjuk cabang di persimpangan jalan, hingga standing banner indoor.', 'Mengombinasikan warna kuning oranye hangat khas kuah sop gurih, maskot Pak Dhe yang ramah, foto mangkuk sop iga mengepul hangat, tipografi melengkung yang bersahabat, serta panah penunjuk jalan merah yang tajam dan kontras.', 'Memudahkan calon pengunjung menemukan lokasi cabang resto dari jalan utama, menciptakan branding outlet yang tertata rapi, dan menaikkan omzet pengunjung jam makan siang secara signifikan.', 'Sop Tangkar Pak Dhe', 2024, 'Outdoor Signage & Banner Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'Spanduk Warung', 'Signage Penunjuk Arah', 'Kuliner Nusantara', 'X-Banner Maksi'], '/portfolio/banners/banner-3.png', NULL, NULL, true, 18, 'published'),
('proj-banner-4', 'Airlangga Gymnasium Promotional Banners', 'airlangga-gymnasium-banners', 'Desain baliho spanduk promo harian & banner motivasi dinding interior gym bertenaga', 'Desain media cetak outdoor dan indoor untuk Airlangga Gymnasium. Terdiri dari spanduk billboard horizontal depan pusat kebugaran dengan promo "Hanya 10 Ribu Harian Sepuasnya" berlogo Airlangga "Sehat Jiwa Raga", serta dua banner dinding motivasi interior bertema "Go Hard or Go Home" (Jay Cutler) dan "Shape Your Body" (Chris Bumstead).', 'Menyampaikan penawaran harga tiket harian gym yang sangat kompetitif dengan visual gagah dan berkelas internasional, serta membangkitkan adrenalin dan semangat para member di ruang latihan beban.', 'Memadukan palet warna hitam industrial dan merah darah dengan tekstur grunge gelap, tipografi headline sans-serif raksasa bergaya athletic gym, serta cutting foto binaragawan legendaris dengan aksen pencahayaan berkarakter kuat.', 'Menarik ratusan pengunjung baru yang ingin mencoba latihan dengan tarif terjangkau serta memperkuat atmosfer maskulin dan penuh motivasi di dalam arena gym.', 'Airlangga Gymnasium', 2024, 'Large Format & Interior Banner Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'Gym Billboard', 'Spanduk Promo', 'Wall Banner Motivasi', 'Fitness Branding'], '/portfolio/banners/banner-4.png', NULL, NULL, true, 19, 'published'),
('proj-banner-5', 'Roti Bang Boy Menu Display & Banners', 'roti-bang-boy-banners', 'Desain spanduk gerai, backdrop menu display etalase lengkap harga, & standing banner promo bakery', 'Paket lengkap media cetak gerai bakery Roti Bang Boy yang meliputi spanduk nama toko "Lembutnya Juara, Lezatnya Tiada Dua!", banner display daftar menu favorit horizontal dengan foto produk dan price list lengkap (Butter Croissant, Roti Artisan, Cinnamon Roll, Pain au Chocolat, dll), serta standing banner vertikal untuk sisi pintu masuk.', 'Menampilkan lebih dari 9 varian menu roti dengan foto close-up detail dan harga masing-masing agar konsumen di depan kasir dan etalase dapat memilih dengan cepat dan nyaman tanpa kebingungan.', 'Merancang sistem layout grid menu berbingkai putih di atas latar merah marun hangat, disertai ilustrasi garis roti artistik, foto produk berbayang realistis, dan tipografi harga yang bersih dan jelas.', 'Membuat tampilan gerai terlihat profesional dan tertata layaknya bakery modern ternama, mempercepat durasi transaksi di kasir, dan meningkatkan kepuasan konsumen.', 'Roti Bang Boy Bakery', 2024, 'Storefront Signage & Price List Banner Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'Spanduk Bakery', 'Menu Display', 'Price List Banner', 'Standing Banner'], '/portfolio/banners/banner-5.png', NULL, NULL, true, 20, 'published'),
('proj-banner-6', 'BTN Properti Lelang', 'btn-properti-lelang-banner', 'Desain spanduk & display banner promosi rumah lelang berkualitas harga terjangkau', 'Desain banner pameran dan materi promosi cetak untuk program BTN Properti Lelang bekerja sama dengan Danantara Indonesia. Menampilkan etalase pilihan terbaik aset rumah lelang hunian (Sentul City Residence, Wartawangsa Residence, dan Griya Savannah) lengkap dengan foto fisik rumah, harga limit di bawah pasar, spesifikasi kamar & luas tanah/bangunan, QR Code katalog lelang, dan kontak PIC tim pemasaran.', 'Menyajikan data teknis properti lelang yang padat (legalitas, limit harga, ukuran LT/LB, dan lokasi wilayah) ke dalam layout banner yang tetap elegan, terpercaya, mudah dibaca cepat oleh calon investor properti, dan sesuai pedoman visual Bank BTN.', 'Menerapkan struktur 3 kolom kartu properti dengan badge "HOT SALE" yang mencolok, palet warna korporat biru khas BTN dan aksen kuning dinamis, penegasan nilai jual (Harga di bawah pasaran, legalitas terjamin), serta call-to-action scan barcode yang responsif.', 'Meningkatkan minat pendaftaran lelang properti dan mempermudah tim pemasaran menjaring calon pembeli potensial pada pameran properti expo dan kantor cabang.', 'Bank BTN & Danantara Indonesia', 2024, 'Property Promo & Banner Layout Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'BTN Properti Lelang', 'Rumah Lelang', 'Real Estate', 'BUMN Branding'], '/portfolio/banners/banner-6.png', NULL, NULL, true, 21, 'published'),
('proj-banner-7', 'Pertamina Corporate Event & Training Banners', 'pertamina-corporate-training-banners', 'Seri desain backdrop panggung, roll-up banner, & spanduk pelatihan BUMN Pertamina Group', 'Koleksi desain backdrop panggung utama dan roll-up banner resmi untuk agenda korporat Pertamina Group (PT Pertamina Patra Niaga, PT Pertamina Trans Kontinental, dan PTC). Meliputi backdrop "Workshop Penulisan Risalah CIP Kantor Pusat & Anak Perusahaan 2025", backdrop maritim "Vessel Operation Performance Training", serta banner program budaya "Strengthen The Role Agent of Change (AoC) Upskilling Brand Guideline".', 'Memenuhi standar brand guideline BUMN Pertamina yang ketat dengan kombinasi logo multi-entitas (Danantara, Pertamina Patra Niaga, PTK, PTC) tanpa membuat layout tampak kaku, sekaligus menampilkan visual pendukung teknis (armada kapal tanker, armada truk tangki, dan personil kerja) yang presisi.', 'Menggunakan komposisi lengkungan dinamis khas Pertamina, gradasi warna biru korporat dan aksen merah energi, pencahayaan panggung yang jernih, tipografi sans-serif resmi berkarakter kokoh, serta penempatan elemen grafis 3D kapal dan avatar personil yang representatif.', 'Memberikan citra acara pelatihan yang prestisius dan profesional bagi seluruh peserta pimpinan dan karyawan, serta menjadi acuan standar visual publikasi internal divisi Human Capital & Quality Management.', 'Pertamina Patra Niaga, PTK & PTC', 2025, 'Corporate Event & Large Format Backdrop Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'Pertamina Group', 'Corporate Backdrop', 'Event BUMN', 'Workshop Training'], '/portfolio/banners/banner-7.png', NULL, NULL, true, 22, 'published'),
('proj-banner-8', 'Griya Nyushi Storefront & Menu Banners', 'griya-nyushi-storefront-banners', 'Paket lengkap spanduk plang gerai khas Jepang, border doodle sushi, & standing banner menu lengkap', 'Paket desain media cetak luar dan dalam ruangan untuk restoran Jepang Griya Nyushi "Japanese Food & Sushi". Terdiri dari spanduk plang nama utama dengan latar ornamen ombak tradisional Seigaiha dan lampion merah chouchin, pita banner border atas-bawah dengan ilustrasi doodle sushi menggemaskan, serta standing banner vertikal "Menu Lengkap Hanya Disini" menampilkan foto chef membawa sajian aneka sushi & sashimi lezat.', 'Menciptakan nuansa kedai makan Jepang yang kental, ramah, dan eye-catching dari pinggir jalan raya, dengan elemen grafis yang bisa disesuaikan secara fleksibel pada kanopi gerai, plang toko, dan standing banner pintu masuk.', 'Penggunaan warna biru royal Jepang yang kontras dengan aksen merah oranye lampion, ornamen sudut awan oriental, barisan line art aneka jenis sushi (nigiri, maki, temaki), serta foto staf chef tersenyum ramah menyajikan menu unggulan.', 'Menciptakan identitas fasad toko yang sangat unik dan instagrammable, membedakan resto dari kompetitor kuliner lainnya, serta memandu pelanggan langsung menuju area kasir dengan informasi menu yang jelas.', 'Griya Nyushi Resto', 2024, 'Japanese Storefront & Banner Signage Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'Japanese Food', 'Spanduk Resto', 'Standing Banner', 'Sushi Signage'], '/portfolio/banners/banner-8.png', NULL, NULL, true, 23, 'published'),
('proj-banner-9', 'Memetri Bumi Pagelaran Wayang Kulit', 'memetri-bumi-wayang-kulit-banner', 'Desain backdrop panggung megah, spanduk jalan, & poster acara tradisi bersih desa pagelaran wayang kulit', 'Desain media publikasi dan backdrop panggung pagelaran seni budaya Memetri Bumi dalam rangka Bersih Desa Dukuh Watulawang, Trosobo. Mengemas acara Pagelaran Wayang Kulit semalam suntuk lakon "Romo Tambak" bersama dalang Ki Bagong Darmono S.H. dan bintang tamu Bagong Glondor. Paket desain mencakup backdrop panggung megah berukuran besar, spanduk jalan horizontal, serta standing banner informasi waktu dan lokasi acara.', 'Menyajikan nuansa keagungan seni tradisi Jawa klasik yang sakral dan meriah namun tetap bersih, rapi, serta mudah dibaca oleh seluruh kalangan masyarakat desa dari kejauhan.', 'Mengolaborasikan ornamen gunungan wayang kulit tatah emas, gapura candi keemasan, pita merah putih peringatan hari kemerdekaan ke-80, efek sinar fajar kejayaan, tipografi 3D kaligrafi modern "Memetri Bumi", serta susunan tokoh wayang Hanoman, Rama, dan Rahwana yang dramatis.', 'Menjadi pusat perhatian utama di panggung pagelaran seni desa, meningkatkan antusiasme kehadiran ratusan warga, serta mendapat apresiasi tinggi dari para tokoh adat dan panitia desa.', 'Panitia Bersih Desa Dukuh Watulawang, Trosobo', 2025, 'Cultural Event & Stage Backdrop Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'Wayang Kulit', 'Backdrop Panggung', 'Budaya Jawa', 'Etnik Tradisional'], '/portfolio/banners/banner-9.png', NULL, NULL, true, 24, 'published'),
('proj-banner-10', 'Wonton Mawon Pangsit Pedas Banners', 'wonton-mawon-pangsit-pedas-banner', 'Paket branding spanduk plang gerai street food & banner etalase menu pangsit pedas level dewa', 'Set lengkap desain materi cetak gerai street food Wonton Mawon "Pangsit Pedas Level Dewa - Resep Dari Hongkong". Terdiri dari spanduk plang nama gerobak/outlet memanjang, banner backdrop dinding menu dengan foto close-up pangsit kuah dan pangsit kering cabai melimpah serba 10 ribuan, serta banner penutup counter etalase lengkap dengan informasi kontak kemitraan franchise.', 'Membangun daya pikat visual instan bagi pecinta jajanan pedas jalanan dan kaum muda, dengan penekanan level kepedasan ekstrem yang bikin penasaran dan harga terjangkau.', 'Memaksimalkan karakter maskot ekspresi kepedasan berkeringat dengan mata berair yang komikal dan memorable, warna merah cabai membara berpadu pola tekstur garis asap mie, badge harga "10K" yang mencolok, dan foto seporsi wonton chili oil yang menggoda selera.', 'Mendongkrak daya tarik gerai kaki lima menjadi tampak rapi dan higienis, meningkatkan omzet penjualan harian, serta menarik puluhan calon mitra waralaba kemitraan baru.', 'Wonton Mawon Street Food', 2024, 'Street Food Branding & Storefront Banner Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'Wonton Mawon', 'Pangsit Pedas', 'Street Food', 'Spanduk Gerai'], '/portfolio/banners/banner-10.png', NULL, NULL, true, 25, 'published'),
('proj-banner-11', 'Bebek Mas Bolot Storefront & Menu Banners', 'bebek-mas-bolot-storefront-banners', 'Desain spanduk gerai utama, banner promo paket hemat, & papan display menu lengkap', 'Paket lengkap desain materi cetak gerai Bebek Mas Bolot yang memadukan tagline jenaka "Cobain dulu, gak perlu teriak biar denger enaknya!". Terdiri dari spanduk plang nama depan toko horizontal berlatar merah pekat dengan deretan 5 menu signature bebek & ayam, banner promo counter "Only Rp 25.000", serta banner display daftar menu lengkap beserta pricelist (bebek sedang, bebek jumbo, bebek utuh, varian bumbu hitam, bumbu laos, bebek bakar, dan aneka sambal botol).', 'Menyusun daftar menu yang sangat variatif dengan detail porsi dan harga yang berbeda-beda ke dalam susunan tabel visual yang rapi, kontras, dan mudah dicerna pelanggan saat berdiri di depan kasir atau memesan dari kendaraan.', 'Menggunakan sistem hierarki warna kartu kuning-putih di atas latar merah marun hangat, dilengkapi foto close-up setiap varian sajian beresolusi tajam, icon saluran online delivery (ShopeeFood, GoFood, GrabFood), serta nomor kontak pemesanan catering yang jelas.', 'Menciptakan kesan outlet kuliner yang profesional, higienis, dan terorganisir rapi, mempercepat proses pemilihan menu di meja kasir, dan menaikkan pesanan paket porsi jumbo dan bebek utuh.', 'Bebek Mas Bolot Kuliner', 2024, 'Food Storefront Signage & Price List Banner Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'Bebek Mas Bolot', 'Spanduk Kuliner', 'Menu Display', 'Price List Banner'], '/portfolio/banners/banner-11.png', NULL, NULL, true, 26, 'published'),
('proj-banner-12', 'Air Jordan Sneakers Promo Banners', 'air-jordan-sneakers-promo-banners', 'Desain web banner & retail display promo sneakers eksklusif Air Jordan edisi terbatas', 'Koleksi desain banner promosi e-commerce dan pameran ritel streetwear untuk lini sneakers legendaris Air Jordan di platform marketplace Farfetch. Menampilkan 3 rilisan siluet ikonik: Air Jordan 1 Retro High X OFF-WHITE Chicago (karya kolaborasi Virgil Abloh), Air Jordan 1 Retro Mid Royal Blue / Laser Orange, serta standing banner vertikal Air Jordan 1 Retro High "New Love" bernuansa kuning hitam tebal.', 'Menonjolkan nilai estetika kemewahan dan hype kultur sneakers street fashion dengan komposisi banner modern yang mengarahkan fokus mata langsung pada detail tekstur material sepatu dan tombol Call-To-Action belanja.', 'Menerapkan split-background colorblocking merah, putih, biru royal, dan kuning berani, dipadukan tipografi tulisan tangan brush dinamis dengan sans-serif modern, logo resmi Jumpman, label harga eksklusif, serta deskripsi spesifikasi edisi terbatas yang informatif.', 'Meningkatkan rasio klik (Click-Through Rate / CTR) pada promosi kampanye rilis sneakers edisi terbatas dan memberikan visual presentasi bertaraf global yang memikat para kolektor sneakers.', 'Farfetch Sneaker Campaign', 2024, 'Sneaker Retail & Digital Banner Designer', 'cat-desain-banner', ARRAY['Desain Banner', 'Air Jordan', 'Sneakers', 'Streetwear', 'E-Commerce Banner'], '/portfolio/banners/banner-12.png', NULL, NULL, true, 27, 'published'),
('proj-pack-1', 'Bebek Mas Bolot Takeaway Box Packaging', 'bebek-mas-bolot-box-packaging', 'Desain pola dieline & mockup 3D kotak kardus tenteng takeaway kuliner bebek olahan', 'Desain kemasan kotak makanan siap bawa (takeaway box) inovatif dengan pegangan tenteng terintegrasi untuk Bebek Mas Bolot. Menampilkan perpaduan pola dieline siap potong dan lipat (die-cut dieline) dalam kombinasi warna merah marun dan kuning cerah. Diperkaya dengan tagline unik "#Rasanya bikin nyambung, walau namanya Bolot!", logo maskot resmi, icon delivery order, dan informasi kontak pemesanan.', 'Merancang kemasan makanan yang fungsional, praktis dibawa tanpa memerlukan kantong plastik tambahan, kokoh menampung berat porsi bebek utuh beserta nasi dan kuah sambal, serta memiliki daya pikat visual yang kuat di jalanan.', 'Mengembangkan konstruksi lipatan interlocking tanpa lem dengan handle pegangan atas yang kokoh, sistem sirkulasi uap makanan, kontras warna yang mudah dikenali saat dibawa kurir atau konsumen, serta penempatan logo dan tagline di setiap sisi bidang lipatan box.', 'Meningkatkan nilai kepuasan unboxing pelanggan pesan-antar, mendukung gerakan ramah lingkungan dengan meminimalkan penggunaan kantong plastik, serta memperkuat promosi brand secara organik di ruang publik.', 'Bebek Mas Bolot Kuliner', 2024, 'Packaging Structural & Graphic Designer', 'cat-desain-label-packaging', ARRAY['Desain Label & Packaging', 'Food Box', 'Takeaway Packaging', 'Dieline Cetak', 'Bebek Mas Bolot'], '/portfolio/packaging/packaging-1.png', NULL, NULL, true, 28, 'published'),
('proj-pack-2', 'Griya Nyushi Window Box Sushi Packaging', 'griya-nyushi-sushi-box-packaging', 'Desain kemasan box sushi takeaway dengan jendela mika transparan & motif etnik Seigaiha', 'Desain packaging box takeaway premium untuk restoran Jepang Griya Nyushi "Japanese Food & Sushi". Mengusung konsep jendela transparan (die-cut clear window) pada bagian atas agar keindahan susunan sushi dan sashimi segar terlihat langsung oleh pembeli. Dibalut warna biru kobalt dan oranye khas Jepang dengan ornamen gelombang ombak Seigaiha dan barisan ikon doodle sushi di sisi samping box.', 'Membuat kemasan makanan khas Jepang yang menjaga kualitas bentuk sushi selama perjalanan pesan-antar, higienis, anti-rembes, sekaligus memperlihatkan estetika kesegaran salmon dan tuna di dalamnya.', 'Merancang pola dieline box lipat presisi dengan laminasi food-grade bagian dalam, jendela mika bening di bagian tutup atas, serta tata letak grafis bertema "Sushi Favorit, Siap Dibawa!" yang rapi dan memikat.', 'Memberikan pengalaman unboxing sushi layaknya bersantap langsung di restoran bintang lima, meningkatkan pesanan hampers sushi ulang tahun/perayaan, dan meningkatkan citra higienis resto.', 'Griya Nyushi Resto', 2024, 'Packaging & Surface Pattern Designer', 'cat-desain-label-packaging', ARRAY['Desain Label & Packaging', 'Sushi Box', 'Window Packaging', 'Japanese Pattern', 'Food Grade Packaging'], '/portfolio/packaging/packaging-2.png', NULL, NULL, true, 29, 'published'),
('proj-pack-3', 'Roti Bang Boy Bakery Box Packaging', 'roti-bang-boy-bakery-box-packaging', 'Desain dus kemasan bakery & hampers roti retro merah marun dengan ilustrasi aneka pastry', 'Desain kemasan dus kotak roti eksklusif untuk Roti Bang Boy berukuran sedang yang cocok untuk isi 6 hingga 10 aneka roti dan pastry. Menggunakan warna merah marun klasik dengan aksen putih bersih. Pada sisi samping dus dihiasi ilustrasi vektor aneka macam roti (croissant, artisan bread, cinnamon roll, kepang wijen), dilengkapi informasi jam operasional toko #BakerySolo (8 AM - 8 PM) dan kontak pemesanan.', 'Menghadirkan packaging box yang terlihat premium dan hangat untuk kebutuhan oleh-oleh atau hampers keluarga, dengan struktur dus yang kuat ditumpuk (stackable) saat pengiriman dalam jumlah banyak.', 'Pola dieline model flap pizza/bakery box lipat otomatis dengan dinding ganda di sisi samping agar kokoh saat ditumpuk, grafis logo maskot di bagian tengah tutup, serta line art menu roti yang estetik di sekeliling bodi dus.', 'Membuat produk Roti Bang Boy sangat diminati sebagai bingkisan hantaran dan oleh-oleh khas kota Solo, serta melindungi tekstur roti agar tetap utuh dan empuk sampai ke tangan pembeli.', 'Roti Bang Boy Bakery', 2024, 'Bakery Packaging & Die-cut Box Designer', 'cat-desain-label-packaging', ARRAY['Desain Label & Packaging', 'Bakery Box', 'Kemasan Roti', 'Dus Hampers', 'Roti Bang Boy'], '/portfolio/packaging/packaging-3.png', NULL, NULL, true, 30, 'published'),
('proj-pack-4', 'Sambel Oma Jar Label & Packaging', 'sambel-oma-jar-label-packaging', 'Desain label stiker botol jar kaca & materi promosi paket hemat sambel terasi cumi nusantara', 'Desain label stiker botol kaca kedap udara untuk varian Sambel Oma "Sambel Terasi Cumi". Mengintegrasikan ilustrasi maskot nenek mengulek sambal cabai dengan elemen lidah api berkobar merah kuning. Label mencakup informasi legalitas produk makanan lengkap: tabel komposisi bahan, saran penyimpanan, saran penyajian lezat, tabel ceklis tanggal kadaluarsa (expired date), serta materi visual iklan 3D paket hemat.', 'Memuat seluruh informasi regulasi label makanan kemasan (komposisi, penyimpanan, barcode/expired date) dalam dimensi stiker botol jar kaca yang terbatas tanpa terlihat sesak, serta tetap terlihat menggugah selera pembeli di etalase toko dan marketplace.', 'Membagi tata letak label stiker menjadi 3 zona: zona depan (maskot & nama produk utama), zona kiri (deskripsi kelezatan & daftar komposisi bahan baku), dan zona kanan (saran konsumsi & tabel masa kadaluarsa) dengan tipografi sans-serif kontras bergaris batas yang jelas.', 'Memberikan impresi produk UMKM berstandar higienis industri modern, siap didistribusikan ke supermarket, minimarket, serta penjualan daring ke seluruh Indonesia.', 'Sambel Oma Nusantara', 2024, 'Jar Label & FMCG Packaging Designer', 'cat-desain-label-packaging', ARRAY['Desain Label & Packaging', 'Label Stiker Botol', 'Sambel Kemasan', 'Jar Packaging', 'UMKM Kuliner'], '/portfolio/packaging/packaging-4.png', NULL, NULL, true, 31, 'published'),
('proj-pack-5', 'Joocy Fresh Juice Bottle Labels', 'joocy-fresh-juice-bottle-labels', 'Desain label stiker botol minuman die-cut arch untuk varian jus buah segar 100% organik', 'Rangkaian desain label stiker botol minuman buah segar untuk brand Joocy "Fresh Juice - New Taste". Terdiri dari 3 varian rasa favorit: Guava Juice (merah muda), Orange Juice (oranye segar), dan Avocado Juice (hijau alpukat lembut). Menampilkan potongan bentuk label melengkung modern (arch die-cut), klaim "100% Organic & Natural Sugar", tipografi vertikal minimalis, serta ilustrasi potongan buah segar yang memicu kesegaran dahaga.', 'Menciptakan citra minuman kesehatan yang segar, modern, dan bergaya hidup sehat bagi kalangan urban muda, dengan desain label yang tahan air dan tidak mudah luntur saat botol didinginkan di dalam chiller.', 'Bentuk pola potong stiker lengkung (arch) yang unik dan kekinian, tipografi sans-serif vertikal di sisi samping, paduan warna cerah yang senada dengan warna asli sari buah, serta logo Joocy bermotif tetesan jus yang playful.', 'Meningkatkan daya saing produk di rak pendingin kafe dan supermarket, menciptakan brand recall yang kuat, serta menjadi materi promosi konten media sosial yang estetik.', 'Joocy Beverage Co.', 2024, 'Beverage Label & Product Packaging Designer', 'cat-desain-label-packaging', ARRAY['Desain Label & Packaging', 'Label Botol Minuman', 'Fresh Juice', 'Die-Cut Label', 'Organic Beverage'], '/portfolio/packaging/packaging-5.png', NULL, NULL, true, 32, 'published');

-- 6. Masukkan Gambar Galeri Proyek (32 foto)
INSERT INTO public.project_images (id, project_id, image_url, caption, sort_order) VALUES
('img-logo-1-1', 'proj-logo-1', '/portfolio/logos/page-1.png', 'Karang Taruna Selo Utomo — Logo Presentation & Detail Filosofi', 1),
('img-logo-2-1', 'proj-logo-2', '/portfolio/logos/page-2.png', 'Hype Steps — Logo Presentation & Brand Symbolism', 1),
('img-logo-3-1', 'proj-logo-3', '/portfolio/logos/page-3.png', 'Sambel Oma — Mascot & Culinary Branding Showcase', 1),
('img-logo-4-1', 'proj-logo-4', '/portfolio/logos/page-4.png', 'Sop Tangkar Pak Dhe — Authentic Culinary Mascot Identity', 1),
('img-logo-5-1', 'proj-logo-5', '/portfolio/logos/page-5.png', 'Ruchi — Cute Mascot & Sweet Bakery Branding', 1),
('img-logo-6-1', 'proj-logo-6', '/portfolio/logos/page-6.png', 'Little Tokyo — Japanese Dining Mascot & Logotype', 1),
('img-logo-7-1', 'proj-logo-7', '/portfolio/logos/page-7.png', 'Roti Bang Boy — Badge Emblem & Packaging Iconography', 1),
('img-logo-8-1', 'proj-logo-8', '/portfolio/logos/page-8.png', 'Ayam Nenek — Mascot Illustration & Traditional Branding', 1),
('img-logo-9-1', 'proj-logo-9', '/portfolio/logos/page-9.png', 'Sahabat Sego Sambel — Fiery Sambal Logo & Presentation', 1),
('img-logo-10-1', 'proj-logo-10', '/portfolio/logos/page-10.png', 'Bebek Mas Bolot — Mascot & Culinary Brand Identity Presentation', 1),
('img-feed-4-1', 'proj-feed-4', '/portfolio/feeds/feed-bebek-mas-bolot.png', 'Bebek Mas Bolot — Mouthwatering Culinary Social Media Feeds', 1),
('img-feed-1-1', 'proj-feed-1', '/portfolio/feeds/feed-airlangga.png', 'Airlangga Gymnasium — Dynamic Fitness Feeds & Social Media Campaign', 1),
('img-feed-5-1', 'proj-feed-5', '/portfolio/feeds/feed-griya-nyushi.png', 'Griya Nyushi — Japanese Culinary Social Media Feeds & Menu Showcase', 1),
('img-feed-3-1', 'proj-feed-3', '/portfolio/feeds/feed-roti-bang-boy.png', 'Roti Bang Boy — Appetizing Culinary Bakery Feeds & Promo Series', 1),
('img-feed-2-1', 'proj-feed-2', '/portfolio/feeds/feed-clovecare.png', 'CloveCare — Fresh & Elegant Skincare Social Media Showcase', 1),
('img-banner-1-1', 'proj-banner-1', '/portfolio/banners/banner-1.png', 'Amanah Frozen Food — Outdoor Spanduk & Standing Banner Set', 1),
('img-banner-2-1', 'proj-banner-2', '/portfolio/banners/banner-2.png', 'Rocket Chicken — Standing Banner Series for Best Seller Combo Deals', 1),
('img-banner-3-1', 'proj-banner-3', '/portfolio/banners/banner-3.png', 'Sop Tangkar Pak Dhe — Complete Signage, Directional Boards & Maksi Banner', 1),
('img-banner-4-1', 'proj-banner-4', '/portfolio/banners/banner-4.png', 'Airlangga Gymnasium — Large Format Billboard & Motivational Wall Banners', 1),
('img-banner-5-1', 'proj-banner-5', '/portfolio/banners/banner-5.png', 'Roti Bang Boy — Storefront Header, Menu Display Board & Standing Banner', 1),
('img-banner-6-1', 'proj-banner-6', '/portfolio/banners/banner-6.png', 'BTN Properti Lelang — Real Estate Auction Promotional Banner Showcase', 1),
('img-banner-7-1', 'proj-banner-7', '/portfolio/banners/banner-7.png', 'Pertamina Group — Corporate Backdrop & Workshop Banner Series', 1),
('img-banner-8-1', 'proj-banner-8', '/portfolio/banners/banner-8.png', 'Griya Nyushi — Japanese Resto Storefront Banner Set & Standing Menu Display', 1),
('img-banner-9-1', 'proj-banner-9', '/portfolio/banners/banner-9.png', 'Memetri Bumi — Cultural Stage Backdrop, Street Banner & Event Poster', 1),
('img-banner-10-1', 'proj-banner-10', '/portfolio/banners/banner-10.png', 'Wonton Mawon — Spicy Wonton Street Food Storefront & Counter Banners', 1),
('img-banner-11-1', 'proj-banner-11', '/portfolio/banners/banner-11.png', 'Bebek Mas Bolot — Outdoor Facade Banner, Promo Board & Comprehensive Menu Price List', 1),
('img-banner-12-1', 'proj-banner-12', '/portfolio/banners/banner-12.png', 'Air Jordan — Hype Sneaker Digital Banners & Vertical Retail Showcase', 1),
('img-pack-1-1', 'proj-pack-1', '/portfolio/packaging/packaging-1.png', 'Bebek Mas Bolot — Takeaway Food Box Dieline Template & 3D Packaging Mockup', 1),
('img-pack-2-1', 'proj-pack-2', '/portfolio/packaging/packaging-2.png', 'Griya Nyushi — Japanese Sushi Takeaway Window Box Dieline & 3D Presentation', 1),
('img-pack-3-1', 'proj-pack-3', '/portfolio/packaging/packaging-3.png', 'Roti Bang Boy — Corrugated Bakery Box Dieline & Stacked Packaging Mockup', 1),
('img-pack-4-1', 'proj-pack-4', '/portfolio/packaging/packaging-4.png', 'Sambel Oma — Glass Jar Sticker Label Layout & Promotional Packaging 3D Visual', 1),
('img-pack-5-1', 'proj-pack-5', '/portfolio/packaging/packaging-5.png', 'Joocy — Organic Juice Bottle Label Collection & Refreshing 3D Packaging Mockup', 1);

-- 7. Masukkan Pengalaman Kerja Asli
INSERT INTO public.experiences (id, position, company, company_url, period, location, description, achievements, is_current, sort_order) VALUES
('exp-1', 'Freelance Graphic Designer', 'Fastwork', 'https://fastwork.id', '2022 — Present', 'Remote', 'Work on various graphic design projects based on individual client briefs and requirements.', ARRAY['Manage the design process from concept development and revisions to final delivery', 'Communicate directly with clients to understand their needs and deliver designs that match their expectations', 'Handle branding, social media, and digital marketing visual collateral'], true, 1),
('exp-2', 'Freelance Graphic Designer', 'Ruang Pro Digital Printing', '', '2023 — 2025', 'Boyolali / Surakarta', 'Created branding, promotional, and print designs based on client needs.', ARRAY['Developed visual concepts and layouts from initial briefs through to final artwork', 'Prepared production-ready files and ensured accurate sizing and print specifications', 'Supervised color separation and large format printing output'], false, 2),
('exp-3', 'Graphic Designer & Production', 'Rony Jaya Digital Printing', '', '2022 — 2023', 'Boyolali', 'Created branding, logo, and promotional designs based on client requirements.', ARRAY['Turned client briefs into practical and visually engaging design concepts', 'Handled client communication, revisions, and final artwork preparation', 'Supported the production process to ensure designs were printed accurately and met quality standards'], false, 3),
('exp-4', 'Sales & Operations Intern', 'PT. Asset Ran Investama', '', '2026', 'Indonesia', 'Assisted with analyzing plant nutritional needs to support healthy growth and crop quality.', ARRAY['Supported Open Farm sales activities through presentations and follow-ups with potential investors', 'Maintained investor data and handled sales administration and documentation'], false, 4);

-- 8. Masukkan Layanan Asli
INSERT INTO public.services (id, title, slug, description, deliverables, icon_name, sort_order) VALUES
('srv-1', 'Branding & Identitas Visual', 'branding-identitas-visual', 'Membangun identitas visual yang konsisten agar sebuah brand terlihat lebih profesional, kuat, dan mudah diingat.', ARRAY['Desain & Redesign Logo', 'Identitas Visual Brand', 'Pemilihan Warna & Tipografi', 'Brand Guideline', 'Stationery & Brand Collateral'], 'Palette', 1),
('srv-2', 'Desain Packaging & Produk', 'desain-packaging-produk', 'Membuat desain kemasan dan kebutuhan visual produk yang menarik, informatif, dan siap diproduksi.', ARRAY['Desain Packaging Makanan & Minuman', 'Label Produk & Sticker', 'Desain Pouch, Box & Paper Bag', 'Mockup Produk', 'Artwork Siap Cetak'], 'Box', 2),
('srv-3', 'Desain Media Sosial & Promosi', 'desain-media-sosial-promosi', 'Menciptakan visual promosi yang membantu bisnis menyampaikan produk, informasi, dan karakter brand dengan lebih menarik.', ARRAY['Instagram Feed & Carousel', 'Poster Promosi', 'Menu & Katalog', 'Banner & Materi Iklan', 'Konten Visual Media Sosial'], 'Share2', 3),
('srv-4', 'Desain Percetakan & Produksi', 'desain-percetakan-produksi', 'Mempersiapkan desain dengan mempertimbangkan kebutuhan produksi, ukuran, material, hingga hasil cetak.', ARRAY['Persiapan File Siap Cetak', 'Brosur, Flyer & Banner', 'Kartu Nama & Stationery', 'Sticker & Merchandise', 'Persiapan Material & Finishing'], 'Printer', 4),
('srv-5', 'Video & Konten Visual', 'video-konten-visual', 'Mengembangkan konten visual bergerak untuk kebutuhan promosi dan media digital.', ARRAY['Editing Video', 'Motion Graphic', 'Video Promosi', 'Reels & Konten Media Sosial', 'Animasi Elemen Grafis'], 'Video', 5);

-- 9. Masukkan Pengaturan Situs
DELETE FROM public.site_settings;
INSERT INTO public.site_settings (id, site_title, site_description, accent_color, social_links) VALUES (
  'settings-1',
  'Bernardusfirman — Senior Graphic Designer & Art Director',
  'Portfolio of Bernardusfirman. 8+ years crafting bespoke brand identities, tactile packaging, editorial design, and visual art direction.',
  '#3682F6',
  '{"behance":"https://behance.net/bernardusfirman","dribbble":"https://dribbble.com/bernardusfirman","instagram":"https://instagram.com/bernardusfirman","linkedin":"https://linkedin.com/in/bernardusfirman"}'::jsonb
);


-- 10. Pastikan hak akses terbuka untuk publik & admin
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
